import React, { useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, Box, ClipboardList, Factory, LayoutDashboard, PackageCheck, RefreshCw, Search, Truck, Warehouse, Zap } from 'lucide-react'
import { api } from './services/api'

const tabs = [
  ['dashboard','Dashboard',LayoutDashboard], ['inventory','Inventory',Box], ['orders','Orders',ClipboardList], ['picking','Fulfillment',PackageCheck], ['exceptions','Exceptions',AlertTriangle], ['analytics','Analytics',Activity]
]

function StatusBadge({value}) { return <span className={`badge status-${String(value).toLowerCase().replaceAll(' ','-')}`}>{value}</span> }
function Metric({label,value,sub,icon:Icon,warning}) { return <div className={`metric ${warning?'metric-warning':''}`}><div className="metric-icon"><Icon size={19}/></div><div><div className="metric-value">{value}</div><div className="metric-label">{label}</div>{sub && <div className="metric-sub">{sub}</div>}</div></div> }
function Card({title,children,action}) { return <section className="card"><div className="card-head"><h3>{title}</h3>{action}</div>{children}</section> }

export default function App(){
  const [tab,setTab]=useState('dashboard'), [dash,setDash]=useState(null), [products,setProducts]=useState([]), [orders,setOrders]=useState([]), [tasks,setTasks]=useState([]), [exceptions,setExceptions]=useState([]), [analytics,setAnalytics]=useState(null), [loading,setLoading]=useState(true), [message,setMessage]=useState(''), [search,setSearch]=useState('')
  const load=async()=>{setLoading(true); try { const [d,p,o,t,e,a]=await Promise.all([api.dashboard(),api.products(),api.orders(),api.tasks(),api.exceptions(),api.analytics()]); setDash(d);setProducts(p);setOrders(o);setTasks(t);setExceptions(e);setAnalytics(a);setMessage('')} catch(err){setMessage(err.message)} finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  useEffect(()=>{ if(!message) return; const x=setTimeout(()=>setMessage(''),4000); return()=>clearTimeout(x)},[message])
  const filteredProducts=useMemo(()=>products.filter(p=>(p.name+' '+p.sku+' '+p.category+' '+p.location).toLowerCase().includes(search.toLowerCase())),[products,search])
  const filteredOrders=useMemo(()=>orders.filter(o=>(o.customer+' '+o.status+' '+o.id).toLowerCase().includes(search.toLowerCase())),[orders,search])
  const urgent=[...orders].filter(o=>o.status!=='Dispatched' && o.priority>=4).slice(0,5)
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Warehouse size={22}/></div><div><b>SmartWarehouse</b><span>Operations OS</span></div></div><div className="warehouse-selector"><span>ACTIVE WAREHOUSE</span><strong>WH-01 · Main FC</strong><small>Single warehouse setup</small></div><nav>{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'nav-item active':'nav-item'} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-bottom"><div className="live-dot"></div><div><b>System live</b><span>Mock operational data</span></div></div></aside>
    <main className="main"><header className="topbar"><div><div className="eyebrow">MAIN FULFILLMENT CENTER</div><h1>{tabs.find(t=>t[0]===tab)?.[1]}</h1></div><div className="top-actions"><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search SKU, order, customer..."/></div><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={18}/></button></div></header>
    {message && <div className="toast"><AlertTriangle size={16}/><span>{message}</span></div>}
    {loading ? <div className="loading">Loading warehouse operations...</div> : <>
      {tab==='dashboard' && <Dashboard dash={dash} orders={orders} urgent={urgent} products={products} exceptions={exceptions} onTab={setTab}/>} 
      {tab==='inventory' && <Inventory products={filteredProducts} refresh={load} />}
      {tab==='orders' && <Orders orders={filteredOrders} products={products} refresh={load} />}
      {tab==='picking' && <Fulfillment tasks={tasks} orders={orders} refresh={load}/>} 
      {tab==='exceptions' && <Exceptions exceptions={exceptions} refresh={load}/>} 
      {tab==='analytics' && <Analytics data={analytics}/>} 
    </>}
    </main></div>
}

function Dashboard({dash,orders,urgent,products,exceptions,onTab}){return <>
  <div className="metrics-grid"><Metric label="Open Orders" value={dash.open_orders} sub={`${dash.products} active SKUs`} icon={ClipboardList}/><Metric label="Available Units" value={dash.available_units} sub={`${dash.inventory_units} physical units`} icon={Box}/><Metric label="Low Stock" value={dash.low_stock} sub={`${dash.out_of_stock} out of stock`} icon={AlertTriangle} warning={dash.low_stock>0}/><Metric label="Open Picking" value={dash.picking_tasks} sub={`${dash.open_exceptions} open exceptions`} icon={PackageCheck}/><Metric label="Fulfillment Rate" value={`${dash.fulfillment_rate}%`} sub="Dispatched / total orders" icon={Truck}/></div>
  <div className="hero-grid"><Card title="Decision Engine" action={<span className="chip"><Zap size={14}/> Rule-based recommendations</span>}><div className="decision"><div className="decision-icon"><Zap/></div><div><h4>Priority-first allocation</h4><p>Urgent orders are evaluated first. Available stock is reserved immediately, shortages are logged as exceptions, and the system continues with a partial allocation rather than silently over-promising.</p><button className="primary" onClick={()=>onTab('orders')}>Review order allocation</button></div></div></Card><Card title="Bottleneck monitor"><div className="bars">{dash.bottlenecks.map(b=><div className="bar-row" key={b.area}><div className="bar-label"><span>{b.area}</span><b>{b.score}</b></div><div className="bar"><span style={{width:`${b.score}%`}}></span></div><small>{b.reason}</small></div>)}</div></Card></div>
  <div className="two-grid"><Card title="Urgent orders" action={<button className="link-btn" onClick={()=>onTab('orders')}>View all</button>}>{urgent.length===0?<Empty/>:<div className="list">{urgent.map(o=><div className="list-row" key={o.id}><div><b>#{String(o.id).padStart(4,'0')} · {o.customer}</b><span>{o.total_items} units · {o.notes || 'Priority order'}</span></div><div className="row-right"><span className={`priority p${o.priority}`}>P{o.priority}</span><StatusBadge value={o.status}/></div></div>)}</div>}</Card><Card title="Inventory risk" action={<button className="link-btn" onClick={()=>onTab('inventory')}>Open inventory</button>}><div className="list">{products.filter(p=>p.low_stock).sort((a,b)=>a.available-b.available).slice(0,5).map(p=><div className="list-row" key={p.id}><div><b>{p.sku} · {p.name}</b><span>{p.location} · reorder at {p.reorder_level}</span></div><div className="stock-risk">{p.available===0?'OUT':`${p.available} left`}</div></div>)}</div></Card></div>
  <Card title="Exception inbox">{exceptions.filter(e=>e.resolution==='Open').slice(0,4).map(e=><div className="exception-line" key={e.id}><div className="severity-dot"></div><div><b>{e.type}</b><span>{e.message}</span></div><em>Decision: {e.decision}</em></div>)}{exceptions.filter(e=>e.resolution==='Open').length===0 && <Empty/>}</Card>
</>}

function Inventory({products,refresh}){const [newOpen,setNewOpen]=useState(false);const [damage,setDamage]=useState(null);return <>
  <div className="section-actions"><div><p className="section-kicker">STOCK CONTROL</p><h2>Inventory visibility</h2><span>Available = physical stock − reserved − damaged</span></div><button className="primary" onClick={()=>setNewOpen(true)}>+ Add SKU</button></div>
  <Card title={`${products.length} SKUs`} action={<span className="chip">Single warehouse · WH-01</span>}><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>Location</th><th>Physical</th><th>Reserved</th><th>Damaged</th><th>Available</th><th>Health</th><th>Action</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.sku}</b></td><td>{p.name}<small>{p.category}</small></td><td>{p.location}</td><td>{p.stock}</td><td>{p.reserved}</td><td>{p.damaged}</td><td><strong>{p.available}</strong></td><td>{p.out_of_stock?<span className="badge status-cancelled">OUT OF STOCK</span>:p.low_stock?<span className="badge status-partial">LOW STOCK</span>:<span className="badge status-allocated">HEALTHY</span>}</td><td><button className="small-btn" onClick={()=>setDamage(p)}>Report damage</button></td></tr>)}</tbody></table></div></Card>
  {newOpen&&<ProductModal close={()=>setNewOpen(false)} refresh={refresh}/>} {damage&&<DamageModal product={damage} close={()=>setDamage(null)} refresh={refresh}/>}</>}

function ProductModal({close,refresh}){const [f,setF]=useState({sku:'',name:'',category:'',location:'',stock:0,reorder_level:10,reorder_qty:20});const save=async()=>{try{await api.createProduct({...f,stock:+f.stock,reorder_level:+f.reorder_level,reorder_qty:+f.reorder_qty});close();refresh()}catch(e){alert(e.message)}};return <Modal title="Add product" close={close}><Form f={f} setF={setF} fields={['sku','name','category','location','stock','reorder_level','reorder_qty']}/><button className="primary full" onClick={save}>Create SKU</button></Modal>}
function DamageModal({product,close,refresh}){const [q,setQ]=useState(1),[r,setR]=useState('Damaged during handling');const save=async()=>{try{await api.damage(product.id,+q,r);close();refresh()}catch(e){alert(e.message)}};return <Modal title={`Report damage · ${product.sku}`} close={close}><p className="helper">This reduces allocatable stock and creates an exception record.</p><label>Quantity<input type="number" min="1" max={product.stock} value={q} onChange={e=>setQ(e.target.value)}/></label><label>Reason<input value={r} onChange={e=>setR(e.target.value)}/></label><button className="primary full" onClick={save}>Record damage</button></Modal>}
function Form({f,setF,fields}){return <div className="form-grid">{fields.map(k=><label key={k}>{k.replaceAll('_',' ')}<input value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}</div>}
function Modal({title,close,children}){return <div className="modal-bg"><div className="modal"><div className="modal-head"><h3>{title}</h3><button onClick={close}>×</button></div>{children}</div></div>}
function Empty(){return <div className="empty">No items to show.</div>}

function Orders({orders,products,refresh}){const [open,setOpen]=useState(false);return <><div className="section-actions"><div><p className="section-kicker">ORDER CONTROL</p><h2>Prioritized order queue</h2><span>1 = lowest priority · 5 = urgent</span></div><button className="primary" onClick={()=>setOpen(true)}>+ Create order</button></div><Card title="Allocation queue" action={<span className="chip">Highest priority first</span>}><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Priority</th><th>Items</th><th>Allocated</th><th>Status</th><th>Decision</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>#{String(o.id).padStart(4,'0')}</b><small>{o.items.map(i=>i.sku).join(', ')}</small></td><td>{o.customer}</td><td><span className={`priority p${o.priority}`}>P{o.priority}</span></td><td>{o.total_items}</td><td>{o.allocated_items}</td><td><StatusBadge value={o.status}/></td><td>{o.status==='Created'||o.status==='Partial'?<button className="small-btn primary-outline" onClick={async()=>{try{const r=await api.allocate(o.id);alert(r.decision+(r.shortages?.length?'\n'+r.shortages.join('\n'):''));refresh()}catch(e){alert(e.message)}}}>Run allocation</button>:<span className="muted">Workflow active</span>}</td></tr>)}</tbody></table></div></Card>{open&&<OrderModal products={products} close={()=>setOpen(false)} refresh={refresh}/>}</>}
function OrderModal({products,close,refresh}){const [customer,setCustomer]=useState(''),[priority,setPriority]=useState(3),[sku,setSku]=useState(products[0]?.sku||''),[qty,setQty]=useState(1),[items,setItems]=useState([]);const add=()=>{setItems([...items,{sku,quantity:+qty}])};const save=async()=>{try{if(!customer||!items.length) return alert('Enter customer and add at least one item');await api.createOrder({customer,priority:+priority,items});close();refresh()}catch(e){alert(e.message)}};return <Modal title="Create customer order" close={close}><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Customer name"/></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}>{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select></label><div className="inline-add"><select value={sku} onChange={e=>setSku(e.target.value)}>{products.map(p=><option key={p.sku}>{p.sku}</option>)}</select><input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><button className="small-btn" onClick={add}>Add</button></div><div className="selected-items">{items.map((i,n)=><div key={n}>{i.sku} × {i.quantity}</div>)}</div><button className="primary full" onClick={save}>Create order</button></Modal>}

function Fulfillment({tasks,orders,refresh}){const open=tasks.filter(t=>t.status!=='Completed');return <><div className="section-actions"><div><p className="section-kicker">FULFILLMENT</p><h2>Floor task board</h2><span>Picking → Packing → Quality Check → Dispatch</span></div></div><div className="kanban">{['Picking','Packing','Quality Check','Dispatch'].map(type=><div className="kanban-col" key={type}><div className="kanban-head"><b>{type}</b><span>{open.filter(t=>t.task_type===type).length}</span></div>{open.filter(t=>t.task_type===type).map(t=><div className="task-card" key={t.id}><div className="task-top"><span className={`priority p${t.priority}`}>P{t.priority}</span><small>Task #{t.id}</small></div><h4>Order #{String(t.order_id).padStart(4,'0')}</h4><span>Assigned: {t.assigned_to}</span><button className="primary full" onClick={async()=>{try{await api.updateTask(t.id,'Completed');refresh()}catch(e){alert(e.message)}}}>Mark complete</button></div>)}</div>)}</div><Card title="Workflow rule"><div className="workflow"><span>Order Created</span><i>→</i><span>Priority</span><i>→</i><span>Allocation</span><i>→</i><span>Picking</span><i>→</i><span>Packing</span><i>→</i><span>QC</span><i>→</i><span>Dispatch</span></div></Card></>}

function Exceptions({exceptions,refresh}){return <><div className="section-actions"><div><p className="section-kicker">EXCEPTION MANAGEMENT</p><h2>Exception → Decision → Resolution</h2><span>Every shortage, damage, or workflow issue gets a traceable response.</span></div></div><Card title="Exception inbox"><div className="table-wrap"><table><thead><tr><th>Type</th><th>Order</th><th>Message</th><th>Decision</th><th>Resolution</th><th>Action</th></tr></thead><tbody>{exceptions.map(e=><tr key={e.id}><td><span className="badge status-partial">{e.type}</span></td><td>{e.order_id?`#${String(e.order_id).padStart(4,'0')}`:'—'}</td><td>{e.message}</td><td>{e.decision}</td><td><StatusBadge value={e.resolution}/></td><td>{e.resolution==='Open'?<button className="small-btn" onClick={async()=>{await api.resolveException(e.id);refresh()}}>Resolve</button>:<span className="muted">Closed</span>}</td></tr>)}</tbody></table></div></Card></>}

function Analytics({data}){if(!data)return null;const statuses=Object.entries(data.orders_by_status);const cats=Object.entries(data.units_by_category);return <><div className="section-actions"><div><p className="section-kicker">OPERATIONS INTELLIGENCE</p><h2>Analytics & bottlenecks</h2><span>Simple operational KPIs derived from the warehouse database.</span></div></div><div className="two-grid"><Card title="Orders by status"><div className="bars">{statuses.map(([k,v])=><div className="bar-row" key={k}><div className="bar-label"><span>{k}</span><b>{v}</b></div><div className="bar"><span style={{width:`${Math.min(v*28,100)}%`}}></span></div></div>)}</div></Card><Card title="Units by category"><div className="bars">{cats.map(([k,v])=><div className="bar-row" key={k}><div className="bar-label"><span>{k}</span><b>{v}</b></div><div className="bar"><span style={{width:`${Math.min(v/Math.max(...cats.map(x=>x[1]))*100,100)}%`}}></span></div></div>)}</div></Card></div><Card title="Top stock risks"><div className="risk-grid">{data.top_stock_risks.map(p=><div className="risk-card" key={p.id}><div><b>{p.sku}</b><span>{p.name}</span></div><strong>{p.available}</strong><small>available / reorder {p.reorder_level}</small></div>)}</div></Card></>}
